version: '2'
services:
  printed_jhipster-app:
    image: printed_jhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://printed_jhipster-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=printed_jhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  printed_jhipster-mongodb:
    extends:
      file: mongodb.yml
      service: printed_jhipster-mongodb
