version: '2'
services:
  printed_jhipster-mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    command: mongos --configdb printed_jhipster-mongodb-config
  printed_jhipster-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  printed_jhipster-mongodb-config:
    image: mongo:4.0.12
    container_name: printed_jhipster-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
